
sudo: required
dist: trusty

language: shell

cache:
   directories:
      - lxc-to-go

script:
      - sudo ./lxc-to-go.sh
      - (echo "proxy"; echo "eth0"; echo "y") | sudo ./lxc-to-go.sh bootstrap
      - echo "--- --- --- --- --- --- --- --- ---"
      - dmesg
      - whoami
      - hostname
      - uname -a

